version: 2.1

orbs:
  python: circleci/python@3.8.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./test_Code.py TestCode
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
